collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.3365557
color:
  saturation: 0.7645667
  brandStrength: 0.9790547
  lightness: 1
  brandColors:
    - '#273816'
    - '#FEFFFF'
    - '#3768AB'
    - '#4F89D5'
    - '#A4ADB4'
  rhythmicContrast: 0.6374866
layout_spectrum: 0.02411149
name: Zappa
